# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade_strategy_param.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trade_strategy_param.proto',
  package='tutorial',
  syntax='proto2',
  serialized_pb=_b('\n\x1atrade_strategy_param.proto\x12\x08tutorial\"\xb4\x02\n\x19\x42uyDropTradeStrategyParam\x12\x16\n\nwatch_time\x18\x01 \x02(\x05:\x02\x33\x30\x12\x1d\n\x0e\x64rop_threshold\x18\x02 \x02(\x02:\x05-0.02\x12)\n\x19watch_time_drop_threshold\x18\x03 \x02(\x02:\x06-0.015\x12$\n\x16rebound_sell_threshold\x18\x04 \x02(\x02:\x04\x30.01\x12\'\n\x18stop_loss_sell_threshold\x18\x05 \x02(\x02:\x05-0.01\x12\x14\n\x08num_slot\x18\x06 \x02(\x05:\x02\x31\x30\x12\x17\n\x0cnum_buy_time\x18\x07 \x02(\x05:\x01\x31\x12\x18\n\rminimal_price\x18\x08 \x02(\x02:\x01\x35\x12\x1d\n\x11minimal_timepoint\x18\t \x02(\x05:\x02\x35\x30')
)




_BUYDROPTRADESTRATEGYPARAM = _descriptor.Descriptor(
  name='BuyDropTradeStrategyParam',
  full_name='tutorial.BuyDropTradeStrategyParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='watch_time', full_name='tutorial.BuyDropTradeStrategyParam.watch_time', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=30,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='drop_threshold', full_name='tutorial.BuyDropTradeStrategyParam.drop_threshold', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(-0.02),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='watch_time_drop_threshold', full_name='tutorial.BuyDropTradeStrategyParam.watch_time_drop_threshold', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(-0.015),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rebound_sell_threshold', full_name='tutorial.BuyDropTradeStrategyParam.rebound_sell_threshold', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(0.01),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stop_loss_sell_threshold', full_name='tutorial.BuyDropTradeStrategyParam.stop_loss_sell_threshold', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(-0.01),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_slot', full_name='tutorial.BuyDropTradeStrategyParam.num_slot', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=10,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_buy_time', full_name='tutorial.BuyDropTradeStrategyParam.num_buy_time', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minimal_price', full_name='tutorial.BuyDropTradeStrategyParam.minimal_price', index=7,
      number=8, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minimal_timepoint', full_name='tutorial.BuyDropTradeStrategyParam.minimal_timepoint', index=8,
      number=9, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=50,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=349,
)

DESCRIPTOR.message_types_by_name['BuyDropTradeStrategyParam'] = _BUYDROPTRADESTRATEGYPARAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BuyDropTradeStrategyParam = _reflection.GeneratedProtocolMessageType('BuyDropTradeStrategyParam', (_message.Message,), dict(
  DESCRIPTOR = _BUYDROPTRADESTRATEGYPARAM,
  __module__ = 'trade_strategy_param_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.BuyDropTradeStrategyParam)
  ))
_sym_db.RegisterMessage(BuyDropTradeStrategyParam)


# @@protoc_insertion_point(module_scope)
