# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sim_environment/simulation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sim_environment/simulation.proto',
  package='tutorial',
  syntax='proto2',
  serialized_pb=_b('\n sim_environment/simulation.proto\x12\x08tutorial\"\x88\x02\n\tPortfolio\x12\x16\n\x0e\x61vailable_cash\x18\x01 \x02(\x02\x12\x0f\n\x07\x62\x61lance\x18\x02 \x02(\x02\x12+\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x1d.tutorial.Portfolio.DataEntry\x1aQ\n\x11OneStockPortfolio\x12\x0e\n\x06volume\x18\x01 \x02(\x05\x12\x15\n\rpurchase_cost\x18\x02 \x02(\x02\x12\x15\n\rcurrent_price\x18\x03 \x02(\x02\x1aR\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x34\n\x05value\x18\x02 \x01(\x0b\x32%.tutorial.Portfolio.OneStockPortfolio:\x02\x38\x01\"\xb5\x01\n\x0bTransaction\x12(\n\x04type\x18\x01 \x02(\x0e\x32\x1a.tutorial.Transaction.Type\x12\x0e\n\x06symbol\x18\x02 \x02(\t\x12\x0e\n\x06\x61mount\x18\x03 \x02(\x05\x12\r\n\x05price\x18\x04 \x02(\x02\x12\x16\n\x0e\x63ommission_fee\x18\x05 \x02(\x02\x12\x0c\n\x04\x64\x61te\x18\x06 \x02(\x05\x12\x0c\n\x04time\x18\x07 \x02(\x05\"\x19\n\x04Type\x12\x07\n\x03\x42UY\x10\x00\x12\x08\n\x04SELL\x10\x01')
)



_TRANSACTION_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='tutorial.Transaction.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BUY', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SELL', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=470,
  serialized_end=495,
)
_sym_db.RegisterEnumDescriptor(_TRANSACTION_TYPE)


_PORTFOLIO_ONESTOCKPORTFOLIO = _descriptor.Descriptor(
  name='OneStockPortfolio',
  full_name='tutorial.Portfolio.OneStockPortfolio',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='volume', full_name='tutorial.Portfolio.OneStockPortfolio.volume', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='purchase_cost', full_name='tutorial.Portfolio.OneStockPortfolio.purchase_cost', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='current_price', full_name='tutorial.Portfolio.OneStockPortfolio.current_price', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=227,
)

_PORTFOLIO_DATAENTRY = _descriptor.Descriptor(
  name='DataEntry',
  full_name='tutorial.Portfolio.DataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='tutorial.Portfolio.DataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='tutorial.Portfolio.DataEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=311,
)

_PORTFOLIO = _descriptor.Descriptor(
  name='Portfolio',
  full_name='tutorial.Portfolio',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='available_cash', full_name='tutorial.Portfolio.available_cash', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='balance', full_name='tutorial.Portfolio.balance', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='tutorial.Portfolio.data', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PORTFOLIO_ONESTOCKPORTFOLIO, _PORTFOLIO_DATAENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=311,
)


_TRANSACTION = _descriptor.Descriptor(
  name='Transaction',
  full_name='tutorial.Transaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='tutorial.Transaction.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='tutorial.Transaction.symbol', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amount', full_name='tutorial.Transaction.amount', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='price', full_name='tutorial.Transaction.price', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='commission_fee', full_name='tutorial.Transaction.commission_fee', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='date', full_name='tutorial.Transaction.date', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='tutorial.Transaction.time', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TRANSACTION_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=495,
)

_PORTFOLIO_ONESTOCKPORTFOLIO.containing_type = _PORTFOLIO
_PORTFOLIO_DATAENTRY.fields_by_name['value'].message_type = _PORTFOLIO_ONESTOCKPORTFOLIO
_PORTFOLIO_DATAENTRY.containing_type = _PORTFOLIO
_PORTFOLIO.fields_by_name['data'].message_type = _PORTFOLIO_DATAENTRY
_TRANSACTION.fields_by_name['type'].enum_type = _TRANSACTION_TYPE
_TRANSACTION_TYPE.containing_type = _TRANSACTION
DESCRIPTOR.message_types_by_name['Portfolio'] = _PORTFOLIO
DESCRIPTOR.message_types_by_name['Transaction'] = _TRANSACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Portfolio = _reflection.GeneratedProtocolMessageType('Portfolio', (_message.Message,), dict(

  OneStockPortfolio = _reflection.GeneratedProtocolMessageType('OneStockPortfolio', (_message.Message,), dict(
    DESCRIPTOR = _PORTFOLIO_ONESTOCKPORTFOLIO,
    __module__ = 'sim_environment.simulation_pb2'
    # @@protoc_insertion_point(class_scope:tutorial.Portfolio.OneStockPortfolio)
    ))
  ,

  DataEntry = _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), dict(
    DESCRIPTOR = _PORTFOLIO_DATAENTRY,
    __module__ = 'sim_environment.simulation_pb2'
    # @@protoc_insertion_point(class_scope:tutorial.Portfolio.DataEntry)
    ))
  ,
  DESCRIPTOR = _PORTFOLIO,
  __module__ = 'sim_environment.simulation_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Portfolio)
  ))
_sym_db.RegisterMessage(Portfolio)
_sym_db.RegisterMessage(Portfolio.OneStockPortfolio)
_sym_db.RegisterMessage(Portfolio.DataEntry)

Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), dict(
  DESCRIPTOR = _TRANSACTION,
  __module__ = 'sim_environment.simulation_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Transaction)
  ))
_sym_db.RegisterMessage(Transaction)


_PORTFOLIO_DATAENTRY.has_options = True
_PORTFOLIO_DATAENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
