# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sim_environment/trade_strategy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sim_environment/trade_strategy.proto',
  package='tutorial',
  syntax='proto2',
  serialized_pb=_b('\n$sim_environment/trade_strategy.proto\x12\x08tutorial\"\xca\x01\n\x14\x42uyDropStrategyParam\x12\x10\n\x08num_slot\x18\x01 \x02(\x05\x12\x19\n\x11minimal_timepoint\x18\x02 \x02(\x05\x12\x15\n\rminimal_price\x18\x03 \x02(\x02\x12\x16\n\x0e\x64rop_threshold\x18\x04 \x02(\x02\x12\x14\n\x0cnum_buy_time\x18\x05 \x02(\x05\x12\x1e\n\x16rebound_sell_threshold\x18\x06 \x02(\x02\x12 \n\x18stop_loss_sell_threshold\x18\x07 \x02(\x02')
)




_BUYDROPSTRATEGYPARAM = _descriptor.Descriptor(
  name='BuyDropStrategyParam',
  full_name='tutorial.BuyDropStrategyParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_slot', full_name='tutorial.BuyDropStrategyParam.num_slot', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minimal_timepoint', full_name='tutorial.BuyDropStrategyParam.minimal_timepoint', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minimal_price', full_name='tutorial.BuyDropStrategyParam.minimal_price', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='drop_threshold', full_name='tutorial.BuyDropStrategyParam.drop_threshold', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_buy_time', full_name='tutorial.BuyDropStrategyParam.num_buy_time', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rebound_sell_threshold', full_name='tutorial.BuyDropStrategyParam.rebound_sell_threshold', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stop_loss_sell_threshold', full_name='tutorial.BuyDropStrategyParam.stop_loss_sell_threshold', index=6,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=253,
)

DESCRIPTOR.message_types_by_name['BuyDropStrategyParam'] = _BUYDROPSTRATEGYPARAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BuyDropStrategyParam = _reflection.GeneratedProtocolMessageType('BuyDropStrategyParam', (_message.Message,), dict(
  DESCRIPTOR = _BUYDROPSTRATEGYPARAM,
  __module__ = 'sim_environment.trade_strategy_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.BuyDropStrategyParam)
  ))
_sym_db.RegisterMessage(BuyDropStrategyParam)


# @@protoc_insertion_point(module_scope)
